"""empty message

Revision ID: 2e887f1a1fbf
Revises: ab147de400bd
Create Date: 2023-04-29 11:47:31.322520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e887f1a1fbf'
down_revision = 'ab147de400bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_message_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('direct_message_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direct_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('last_sent_message_timestamp', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_messages')
    op.drop_table('direct_message_members')
    # ### end Alembic commands ###
